# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash # Implies `set -eo pipefail`, among other things. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell

env:
  CI: 1

jobs:
  build-x86_64-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        submodules: recursive

    - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      with:
        tool-cache: true
    
    - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # 31.3.30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          substituters = https://cache.nixos.org https://mzabani.cachix.org https://cache.iog.io
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= mzabani.cachix.org-1:wnkKakfl+rbT7zTtV1P1tAtjBTuh6GQVX7LfSd9sMbA= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Build hpgsql
      run: nix-build --no-out-link -A hpgsql

    - name: Build benchmarks
      run: nix-build --no-out-link -A hpgsql-benchmarks

    - name: Run tests
      run: |
        nix-env -iA concurrently -f ./nix/nixpkgs.nix
        concurrently -g --timings --names pg16,pg15,pg14,pg13 \
          'scripts/ci/run-tests-and-annotate-with-error.sh local/pg16-tests.txt nix-build --no-out-link -A testsPg16' \
          'scripts/ci/run-tests-and-annotate-with-error.sh local/pg15-tests.txt nix-build --no-out-link -A testsPg15' \
          'scripts/ci/run-tests-and-annotate-with-error.sh local/pg14-tests.txt nix-build --no-out-link -A testsPg14' \
          'scripts/ci/run-tests-and-annotate-with-error.sh local/pg13-tests.txt nix-build --no-out-link -A testsPg13'

  build-aarch64-darwin:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        submodules: recursive

    - name: Recover disk space
      run: |
          df -h
          ls /Applications
          brew uninstall google-chrome
          sudo rm -rf /Users/runner/Library/Android
          sudo rm -rf /Applications/Xcode*
          sudo rm -rf /Applications/Python*
          ls /Applications
          df -h
    
    - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # 31.3.30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          substituters = https://cache.nixos.org https://mzabani.cachix.org https://cache.iog.io
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= mzabani.cachix.org-1:wnkKakfl+rbT7zTtV1P1tAtjBTuh6GQVX7LfSd9sMbA= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: List locales
      run: locale -a

    - name: Print some possibly useful limits
      run: |
        # According to https://doc.owncloud.com/server/next/admin_manual/troubleshooting/path_filename_length.html
        # Macs do have an undocumented limit of 1024 bytes for file paths.
        # If this is true, then it can explain some not-so-occasional test failures
        # we see for Mac. So we print this here, and a few other interesting limits.
        getconf NAME_MAX /
        getconf PATH_MAX /
        ulimit -n # Max number of open file descriptors

    - name: Build hpgsql
      run: nix-build --no-out-link -A hpgsql

    - name: Run tests
      run: |
        # Postgres-version dependent tests for each possible version next
        # We test the last version with the vanilla nixpkgs-built derivation,
        # not the IOHK one. We assume differences in the codebase regarding different
        # postgres versions aren't enough to make it worth testing every version here too.
        # We don't run these concurrently because Nix does not have a sandbox in Macs, so it's
        # not worth the risk.
        scripts/ci/run-tests-and-annotate-with-error.sh local/pg16Nixpkgs-tests.txt nix-build ./nix/install-codd-nixpkgs.nix --no-out-link -A coddWithCheck
        scripts/ci/run-tests-and-annotate-with-error.sh local/pg15-tests.txt nix-build --no-out-link -A testsPg15
        scripts/ci/run-tests-and-annotate-with-error.sh local/pg14-tests.txt nix-build --no-out-link -A testsPg14
        scripts/ci/run-tests-and-annotate-with-error.sh local/pg13-tests.txt nix-build --no-out-link -A testsPg13
